export enum SERVER_EVENT_ENUM {
    SESSION_INIT = 'SESSION_INIT',
    ROOM_CREATED = 'ROOM_CREATED',
    ROOM_JOINED = 'ROOM_JOINED',
    PLAYER_JOINED = 'PLAYER_JOINED',
    PLAYER_LEFT = 'PLAYER_LEFT',
    PLAYER_RECONNECTED = 'PLAYER_RECONNECTED',

    GAME_STARTED = 'GAME_STARTED',
    ROUND_STARTED = 'ROUND_STARTED',


    HINT_REVEALED = 'HINT_REVEALED',
    ROUND_ENDED = 'ROUND_ENDED',
    GAME_ENDED = 'GAME_ENDED',

    WORD_TO_DRAW = 'WORD_TO_DRAW', // sent to drawer only
    WORD_HINT = 'WORD_HINT', // sent to everyone except drawer
    WORD_OPTIONS = 'WORD_OPTIONS', // for drawer
    WAITING_FOR_WORD = 'WAITING_FOR_WORD', // for guesesrs

    CANVAS_UPDATED = 'CANVAS_UPDATED',
    CANVAS_CLEARED = 'CANVAS_CLEARED',
    STROKE_UNDONE = 'STROKE_UNDONE',
    PLAYER_GUESSED = 'PLAYER_GUESSED',
    SCORE_UPDATED = 'SCORE_UPDATED',
    CHAT_MESSAGE = 'CHAT_MESSAGE',
    ERROR = 'ERROR',

    TIMER_SYNC = 'TIMER_SYNC',
    TURN_TIMEOUT = 'TURN_TIMEOUT',

}
