export enum CLIENT_EVENT_ENUM {
    CREATE_ROOM = 'CREATE_ROOM',
    JOIN_ROOM = 'JOIN_ROOM',
    LEAVE_ROOM = 'LEAVE_ROOM',
    START_GAME = 'START_GAME',
    SELECT_WORD = 'SELECT_WORD',
    DRAW_STROKE = 'DRAW_STROKE',
    CLEAR_CANVAS = 'CLEAR_CANVAS',
    UNDO_STROKE = 'UNDO_STROKE',
    SUBMIT_GUESS = 'SUBMIT_GUESS',
    RECONNECT = 'RECONNECT',
    CHAT_MESSAGE = 'CHAT_MESSAGE',
}
